---
with-expecter: True
filename: "{{ .InterfaceName | snakecase }}.go"
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/Zampfi/citadel:
    config:
      dir: "mocks/{{.InterfaceDirRelative}}"
      all: True
      recursive: True