---
with-expecter: True
filename: "{{ .InterfaceName | snakecase }}.go"
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/Zampfi/citadel/workflows/client:
    config:
      dir: "mocks"
      all: True
      recursive: True