// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock_client

import (
	context "context"

	models "github.com/Zampfi/citadel/workflows/models"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockClient) Close(ctx context.Context) {
	_m.Called(ctx)
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Close(ctx interface{}) *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockClient_Close_Call) Run(run func(ctx context.Context)) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func(context.Context)) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with given fields: ctx, params
func (_m *MockClient) Connect(ctx context.Context, params models.ConnectClientParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ConnectClientParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.ConnectClientParams
func (_e *MockClient_Expecter) Connect(ctx interface{}, params interface{}) *MockClient_Connect_Call {
	return &MockClient_Connect_Call{Call: _e.mock.On("Connect", ctx, params)}
}

func (_c *MockClient_Connect_Call) Run(run func(ctx context.Context, params models.ConnectClientParams)) *MockClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ConnectClientParams))
	})
	return _c
}

func (_c *MockClient_Connect_Call) Return(_a0 error) *MockClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Connect_Call) RunAndReturn(run func(context.Context, models.ConnectClientParams) error) *MockClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// StartAsyncWorkflow provides a mock function with given fields: ctx, params
func (_m *MockClient) StartAsyncWorkflow(ctx context.Context, params models.StartWorkflowParams) (models.StartWorkflowResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StartAsyncWorkflow")
	}

	var r0 models.StartWorkflowResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.StartWorkflowParams) (models.StartWorkflowResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.StartWorkflowParams) models.StartWorkflowResponse); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.StartWorkflowResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.StartWorkflowParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_StartAsyncWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAsyncWorkflow'
type MockClient_StartAsyncWorkflow_Call struct {
	*mock.Call
}

// StartAsyncWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.StartWorkflowParams
func (_e *MockClient_Expecter) StartAsyncWorkflow(ctx interface{}, params interface{}) *MockClient_StartAsyncWorkflow_Call {
	return &MockClient_StartAsyncWorkflow_Call{Call: _e.mock.On("StartAsyncWorkflow", ctx, params)}
}

func (_c *MockClient_StartAsyncWorkflow_Call) Run(run func(ctx context.Context, params models.StartWorkflowParams)) *MockClient_StartAsyncWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.StartWorkflowParams))
	})
	return _c
}

func (_c *MockClient_StartAsyncWorkflow_Call) Return(_a0 models.StartWorkflowResponse, _a1 error) *MockClient_StartAsyncWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_StartAsyncWorkflow_Call) RunAndReturn(run func(context.Context, models.StartWorkflowParams) (models.StartWorkflowResponse, error)) *MockClient_StartAsyncWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// StartSyncWorkflow provides a mock function with given fields: ctx, params
func (_m *MockClient) StartSyncWorkflow(ctx context.Context, params models.StartWorkflowParams) (models.StartWorkflowResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StartSyncWorkflow")
	}

	var r0 models.StartWorkflowResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.StartWorkflowParams) (models.StartWorkflowResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.StartWorkflowParams) models.StartWorkflowResponse); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.StartWorkflowResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.StartWorkflowParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_StartSyncWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSyncWorkflow'
type MockClient_StartSyncWorkflow_Call struct {
	*mock.Call
}

// StartSyncWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.StartWorkflowParams
func (_e *MockClient_Expecter) StartSyncWorkflow(ctx interface{}, params interface{}) *MockClient_StartSyncWorkflow_Call {
	return &MockClient_StartSyncWorkflow_Call{Call: _e.mock.On("StartSyncWorkflow", ctx, params)}
}

func (_c *MockClient_StartSyncWorkflow_Call) Run(run func(ctx context.Context, params models.StartWorkflowParams)) *MockClient_StartSyncWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.StartWorkflowParams))
	})
	return _c
}

func (_c *MockClient_StartSyncWorkflow_Call) Return(_a0 models.StartWorkflowResponse, _a1 error) *MockClient_StartSyncWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_StartSyncWorkflow_Call) RunAndReturn(run func(context.Context, models.StartWorkflowParams) (models.StartWorkflowResponse, error)) *MockClient_StartSyncWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
